sudo: false

addons:
  apt:
    packages:
    - curl
    - python-pip
    - oracle-java8-installer

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

# Don't build branches/tags that match this regex. It's the convention used
# for tagging releases, which should be already tested before tagging.
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # These should track with the elasticsearch version
    - MAJOR_VERSION=5
    - MINOR_VERSION=5
    - PATCH_VERSION=2
    - SWOOP_RELEASE_BRANCH=master
    - PADDED_TRAVIS_BUILD_NUMBER=$(printf "%03d" $TRAVIS_BUILD_NUMBER)
    - SWOOP_PROJECT_VERSION="$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION-swoop$PADDED_TRAVIS_BUILD_NUMBER"

    - secure: "P4GeGRK7lREsRNP45PxuzgnpWeiLqhhUPe5xDZuz0uYgnviw6yxb4zdEh272clddMW1eJIWUUQwzidKNuNDSFRMD2+O6U9v1gyNNvAYtIzTkHUu5yjGGF4X/V6+1s9K1CARuSrOUZkqQ4/iCNcS/HlJz0nk5hhmuScLbVh5Zae1ddZWGFlzULSxnKDBvrxIMI83qU6LcY1+yU2Dy1GVhYVXZSxwXSWigKugcFsiLiEG5amvaKRxlAHGRZENzlWDgcLtzN3SfOEck8I0ou+fYybcWERQ2aRTgwb69zw7PSpH9CjPfTtNJ5PjofkBhkfBiidII6WjIkn3MyVhomLtPllQw6jXu2C30Vrn4BwccKGnKcnVx4OoK0NsWTS3xMSaw+DHM+0r86tWXA6+9f7ghfWIYXfwe+uRsHuOtqpRvLPPpkyW/E1m+EqPo2CzQyDyFEH+5MfdhxFddcLjOOPghnN5yTPfcOgYQNWLMtcGjtc1wLLv063L8wkGCcghRUZDLMQTVasSTndeutuNXbOWnrFvUx93QaDsAN9T/t8am7kW7BVjvMmYjTZDIVZriOidFjZGBE+LMavnaa4uYw/fSoWDWGGUHmb0m64aQlxq6ICHrr1LI+OQ1krWJQ4Qh9ka3YEyR82E+3zJRfb7KgpCov73yx9CJtqYNd7rcIm0CD08="
    - secure: "lzfgkyl0E0+z/Un3UyFfnginduDJoMezW5FtUuW/iz/tW7AXW9nb0sulj5DCTX66djKRMTYWn1sSV1IXMK4NSdjTxHzq/HHuqjkfHtDO/a+M5cjLciotFMhTsfabH12l5Cgwdf2fhgJqjEaPCBq+eythLDr/azZLcQFXLVZs7NLKMXYP5NwcRyIqwbqM229sW+vz0UGqA2++4nGGzgeNukUw57bld43aPSfWJpagHlOvabSXI3kEaKcSUFkYyGRZ8e5ah1gv+dkQGwpfaYD4z1xLPW5MMwd8UdhzLB9ANXT6GzAcmmhKa8UllEeiQhdvfPQCCROd4YVCXo+K9Q6zjBVj/Kc74Wo1E8z8mBAqZMGQ8VHdUSZSPyhTEdDRUdKctDYTO6yndd7n3SyVcMfqou7uLZI+PVgvsLj5SspO+0HXlmePG95coibXguOEnqRs//e48ehpMV7eXPCAzzirf5RNchm4/zKpwqZKxyPXxbJfGMC3qkaiYxNg3qjl3peehBAtamR6/NoZb1TBY7jyzHobliYC583JhTpoyymDa85DLWDkOHMu2d0TdwMIE8xuZX1rUO+LQxv6yScYVviFsqb+9M3NtTXIdXCaEGVEIf+Jnl9MMzCHl4yRm7FZCKO8IZhwl0KV6VoEgAbGH4VnpBtMALIo920KL0Xgobvl9II="

    - secure: "RYYhu5QLgQgqD0ac3SOLujhqXmFYk9/Tn0GUAYmtPPOmdE4EnhnBHV5IGTE2YpWlbOkE5tC1MMuhfLAwT6c8lnTp8Zp092KRpq467iWPru+JAbAmTt74XUsFtw0cYX+KNIgLIOag17iXLGQ/cwohPRKObVn6nZ8V2PFwfAxjueY6O1iiRLYUvB01DrfPLArV2LXPGb3NEKxovvk5lS8p9Q1nvNv3epLZ/j0mELGCCyq0nBFZVQ5FKreNiw0ZdnsxKvj625PaYrVWMlwH2uXUsHw1pzCBBddbuxTE1F3sBECoHIUVTRcj+ExNUO8OCI3CZfIYHyrXUBNM85iDlnpFTWzl3MyaZVIRMPwUy8YsqjLs8jZRepNbbEJLJKZ6A7coeo5uJWoP2qBZaw893g8T8CymNToqKzTBV6N1GkDIhZ0zbKU0mAh9tYR9I2w3I3OZQKNdV+ede26WP3BlTz6HfkOxdYxzfepx6l3tYaCGiX37Nvp0LvkooDU22wNY0fHkP60Le55WvHCf2rywafOOHu4nhDJOsTOu3P+FI+vmHyseBJdDSIKHvE12S9t2WR1S6ZUn+jTSKldYPalHm6jFsx0ZaCB3mOi4bGKe9AvcbpUPXEZ4Gn30/tDaWfW/1F8GzyStyGAX56/EBVR9/WoXiQBxs/r76jkFjMNUM5mujLQ="

before_install:
  - wget https://s3.amazonaws.com/swoop-maven/settings.xml -O $HOME/.m2/settings.xml

# Set the Maven version to have the minor version be the Travis build number
before_script:
  - >
    if [ ${TRAVIS_BRANCH} = ${SWOOP_RELEASE_BRANCH} ]
      then mvn versions:set -DnewVersion=${SWOOP_PROJECT_VERSION}
      else mvn versions:set -DnewVersion=${SWOOP_PROJECT_VERSION}-SNAPSHOT
    fi

# after_success:
  # Maven deployments will always happen, but commits to anywhere other than
  # the designated release branch will be snapshot releases.
  # - mvn -DskipTests=true deploy

  # Where the deployment actually happens. Will only deploy off the specified
  # branch, and tag the version in Github
  # - >
  #   [ ${TRAVIS_PULL_REQUEST} = 'false' -a ${TRAVIS_BRANCH} = ${SWOOP_RELEASE_BRANCH} ] &&
  #   curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" -X POST "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/releases" -d '{
  #     "tag_name": "v'"${SWOOP_PROJECT_VERSION}"'",
  #     "target_commitish": "'"${TRAVIS_COMMIT}"'",
  #     "name": "v'"${SWOOP_PROJECT_VERSION}"'",
  #     "body": "https://travis-ci.org/'"${TRAVIS_REPO_SLUG}"'/builds/'"${TRAVIS_BUILD_ID}"'",
  #     "prerelease": false
  #   }'
