sudo: false

addons:
  apt:
    packages:
    - curl
    - python-pip
    - oracle-java8-installer

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

# Don't build branches/tags that match this regex. It's the convention used
# for tagging releases, which should be already tested before tagging.
branches:
  except:
    - /^v[0-9]/

env:
  global:
    - SWOOP_PROJECT_NAME=swoop-es-plugin
    # These should track with the elasticsearch version
    - MAJOR_VERSION=5
    - MINOR_VERSION=6
    - PATCH_VERSION=1
    - SWOOP_RELEASE_BRANCH=master
    - PADDED_TRAVIS_BUILD_NUMBER=$(printf "%03d" $TRAVIS_BUILD_NUMBER)
    - SWOOP_PROJECT_VERSION="$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION-swoop$PADDED_TRAVIS_BUILD_NUMBER"

    - secure: "P4GeGRK7lREsRNP45PxuzgnpWeiLqhhUPe5xDZuz0uYgnviw6yxb4zdEh272clddMW1eJIWUUQwzidKNuNDSFRMD2+O6U9v1gyNNvAYtIzTkHUu5yjGGF4X/V6+1s9K1CARuSrOUZkqQ4/iCNcS/HlJz0nk5hhmuScLbVh5Zae1ddZWGFlzULSxnKDBvrxIMI83qU6LcY1+yU2Dy1GVhYVXZSxwXSWigKugcFsiLiEG5amvaKRxlAHGRZENzlWDgcLtzN3SfOEck8I0ou+fYybcWERQ2aRTgwb69zw7PSpH9CjPfTtNJ5PjofkBhkfBiidII6WjIkn3MyVhomLtPllQw6jXu2C30Vrn4BwccKGnKcnVx4OoK0NsWTS3xMSaw+DHM+0r86tWXA6+9f7ghfWIYXfwe+uRsHuOtqpRvLPPpkyW/E1m+EqPo2CzQyDyFEH+5MfdhxFddcLjOOPghnN5yTPfcOgYQNWLMtcGjtc1wLLv063L8wkGCcghRUZDLMQTVasSTndeutuNXbOWnrFvUx93QaDsAN9T/t8am7kW7BVjvMmYjTZDIVZriOidFjZGBE+LMavnaa4uYw/fSoWDWGGUHmb0m64aQlxq6ICHrr1LI+OQ1krWJQ4Qh9ka3YEyR82E+3zJRfb7KgpCov73yx9CJtqYNd7rcIm0CD08="
    - secure: "lzfgkyl0E0+z/Un3UyFfnginduDJoMezW5FtUuW/iz/tW7AXW9nb0sulj5DCTX66djKRMTYWn1sSV1IXMK4NSdjTxHzq/HHuqjkfHtDO/a+M5cjLciotFMhTsfabH12l5Cgwdf2fhgJqjEaPCBq+eythLDr/azZLcQFXLVZs7NLKMXYP5NwcRyIqwbqM229sW+vz0UGqA2++4nGGzgeNukUw57bld43aPSfWJpagHlOvabSXI3kEaKcSUFkYyGRZ8e5ah1gv+dkQGwpfaYD4z1xLPW5MMwd8UdhzLB9ANXT6GzAcmmhKa8UllEeiQhdvfPQCCROd4YVCXo+K9Q6zjBVj/Kc74Wo1E8z8mBAqZMGQ8VHdUSZSPyhTEdDRUdKctDYTO6yndd7n3SyVcMfqou7uLZI+PVgvsLj5SspO+0HXlmePG95coibXguOEnqRs//e48ehpMV7eXPCAzzirf5RNchm4/zKpwqZKxyPXxbJfGMC3qkaiYxNg3qjl3peehBAtamR6/NoZb1TBY7jyzHobliYC583JhTpoyymDa85DLWDkOHMu2d0TdwMIE8xuZX1rUO+LQxv6yScYVviFsqb+9M3NtTXIdXCaEGVEIf+Jnl9MMzCHl4yRm7FZCKO8IZhwl0KV6VoEgAbGH4VnpBtMALIo920KL0Xgobvl9II="

    - secure: "RYYhu5QLgQgqD0ac3SOLujhqXmFYk9/Tn0GUAYmtPPOmdE4EnhnBHV5IGTE2YpWlbOkE5tC1MMuhfLAwT6c8lnTp8Zp092KRpq467iWPru+JAbAmTt74XUsFtw0cYX+KNIgLIOag17iXLGQ/cwohPRKObVn6nZ8V2PFwfAxjueY6O1iiRLYUvB01DrfPLArV2LXPGb3NEKxovvk5lS8p9Q1nvNv3epLZ/j0mELGCCyq0nBFZVQ5FKreNiw0ZdnsxKvj625PaYrVWMlwH2uXUsHw1pzCBBddbuxTE1F3sBECoHIUVTRcj+ExNUO8OCI3CZfIYHyrXUBNM85iDlnpFTWzl3MyaZVIRMPwUy8YsqjLs8jZRepNbbEJLJKZ6A7coeo5uJWoP2qBZaw893g8T8CymNToqKzTBV6N1GkDIhZ0zbKU0mAh9tYR9I2w3I3OZQKNdV+ede26WP3BlTz6HfkOxdYxzfepx6l3tYaCGiX37Nvp0LvkooDU22wNY0fHkP60Le55WvHCf2rywafOOHu4nhDJOsTOu3P+FI+vmHyseBJdDSIKHvE12S9t2WR1S6ZUn+jTSKldYPalHm6jFsx0ZaCB3mOi4bGKe9AvcbpUPXEZ4Gn30/tDaWfW/1F8GzyStyGAX56/EBVR9/WoXiQBxs/r76jkFjMNUM5mujLQ="

    - secure: "YVTcmGlMz2poKUkF9K8itPk2mb9aFvLZnZJFi/ZFdp8bkCOPQYUZKtJbGtNrmHQ9qmkQ9dO39fa4o4hqgAd6oC97B7QfYyZ+xxQyoyc8pjksIdEV5xpO/LNFF/KhOq8LOtXeXDKgAzMcW1/Nwf+BR0TIm71W8C5iQrEflQLSWvTFnJT5rlPeLzS6XIAtEzC0eZ2r8PNS94er+Uf5ePu2Iskn5z70Xa2MX6Abhb7jYpAhecdcwnXHcW4TpKdQf184Cv6rhrpxq5tS/2KfpEuKWYMJFmkVAM4lwzNtaiRknd5kq6pv/giHN/16dp7AanwP2aTSqzaFeyY/QvqfIZQZExpdfD8JDHlatVUfS06XEWNP8jhF/9e90qos+vHxRsXxys9jDQOdI0abE6ZkrQ1vsfzOSrH6nxhXOvLvvSBj0DKxYYs02cHviB/VzK+61yIA2XHhVtdIlyH/DxKEM7X+RdwF4+vL/GOp68ytUngzhMXds9nSPyBRQbOiWrmkn5yc1QAIKBEqETPUki32zPIJFz7FefGqtEjxGF1s/lQDdZUjCyYSYe03ljP8loCT1NuGsgmOXnoItCJXjXeG08zhWjbAOoApJe4j7VgTTqcOLyiqlEyzVFJyetV1bD7hP78l7SoUFMUDz2KH4fKCNZIgdRXIw489X9/0E3hjgYdbtT4="
    - secure: "EXvZhK7GP+HblhRdtYIhhm0+jc/nI7oA6P6yXyAp02lemkm7QBqPbZJimnamOyXPryX7pRacEKJZDxtaGEscirAWMlthwKatPqliWnq3I+hKsArAEgVJ6VGfD1AkFvOQ8PiS8k/GxZy/ZurKF+5/MohjyAnuU4zuzkzmFFU4peE9NfxYygUcK4FWVR9kiOyTF0BH4UWAga81DHi7ggvUylBDAD4fhSt0h0yRViJOKPORhEcdRyV2ZyGCV1v/vRXbpiH7rRtsGRkO0k7Dc8UxeHTt1keP5omnt5ZR6xsA6igUjDdLDveSXlBXAnnr48mT6YU2Qujfan+2hu4WXhR0BbXRQxOtrPidBI4W2EnnP3K2m6vBvqoa5AfBLNqfnNXIhdhk4UzgpAFVon/GXCZeYpCfqpCc74y14vRFR6rjjRIFHrg+209V0AJR4CXNrw1vQbrJyHOWqgfDNxXY/ZYgmDrLcg8hV5DC5Qvkt//BqddJ0HS5vJy9hW73n0jXj68ujWnWEji4hEllGTVh68fPw6mqZOG6+8f3vrnFKh+QyLCRV9e3Qv/dXMLFN39ynJwpvHYAqqOW4dO3OetTpkzYDHLK7cDtqI55llj6pn0xHcOTLgCVXmpNu5iEo0MPfQvjo0pltz4Jc8HR5okhKSmQr0zvy7RQ/tPXEZgFr3d5lGE="

before_install:
  - wget https://s3.amazonaws.com/swoop-maven/settings.xml -O $HOME/.m2/settings.xml

# Set the Maven version to have the minor version be the Travis build number
before_script:
  - >
    if [ ${TRAVIS_BRANCH} = ${SWOOP_RELEASE_BRANCH} ]
      then mvn versions:set -DnewVersion=${SWOOP_PROJECT_VERSION}
      else mvn versions:set -DnewVersion=${SWOOP_PROJECT_VERSION}-SNAPSHOT
    fi

after_success:
  # Maven deployments will always happen, but commits to anywhere other than
  # the designated release branch will be snapshot releases.
  - mvn -DskipTests=true deploy >/dev/null

  # Where the deployment actually happens. Will only deploy off the specified
  # branch, and tag the version in Github
  - >
    [ ${TRAVIS_PULL_REQUEST} = 'false' -a ${TRAVIS_BRANCH} = ${SWOOP_RELEASE_BRANCH} ] &&
    curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" -X POST "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/releases" -d '{
      "tag_name": "v'"${SWOOP_PROJECT_VERSION}"'",
      "target_commitish": "'"${TRAVIS_COMMIT}"'",
      "name": "v'"${SWOOP_PROJECT_VERSION}"'",
      "body": "https://travis-ci.org/'"${TRAVIS_REPO_SLUG}"'/builds/'"${TRAVIS_BUILD_ID}"'",
      "prerelease": false
    }' &&
    echo "${SWOOP_PROJECT_VERSION}" > /tmp/${SWOOP_PROJECT_NAME}-VERSION &&
    pip install --user --upgrade pip awscli &&
    aws s3api put-object --bucket swoop-deploy --key releases/${SWOOP_PROJECT_NAME} --content-type text/plain --acl public-read --body /tmp/${SWOOP_PROJECT_NAME}-VERSION
